// SPDX-License-Identifier: GPL-2.0
/* jz_sniffer_detect.bpf.c -- Network sniffer detection via ARP probes
 *
 * Stage 24 in the jz_sniff_rn ingress pipeline (rSwitch user module).
 *
 * Detects likely promiscuous-mode sniffers by watching ARP replies to
 * non-existent IP probes generated by user-space sniffd.
 *
 * Pipeline flow:
 *   guard_classifier(21) -> arp_honeypot(22) / icmp_honeypot(23)
 *                        -> sniffer_detect(24)
 *                        -> traffic_weaver(25)
 */

#define  __RSWITCH_MAPS_H      /* non-extern pipeline maps defined in jz_maps.h */
#include "rswitch_module.h"    /* rSwitch SDK v2.1.0: ABI types, CO-RE helpers, pipeline macros */
#include "jz_common.h"
#include "jz_maps.h"
#include "jz_events.h"

/* -- Module Declaration -- */

RS_DECLARE_MODULE("jz_sniffer_detect",
                  RS_HOOK_XDP_INGRESS,
                  JZ_STAGE_SNIFFER_DETECT,
                  RS_FLAG_NEED_L2L3_PARSE | RS_FLAG_CREATES_EVENTS,
                  "Network sniffer detection via ARP probes");

RS_DEPENDS_ON("jz_guard_classifier");

/* -- BPF Maps (module-specific instances) -- */

/* Probe targets -- non-existent IPs that were actively probed */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);                     /* probe IP */
    __type(value, struct jz_probe_target);
    __uint(max_entries, JZ_MAX_PROBE_TARGETS);
    __uint(pinning, LIBBPF_PIN_BY_NAME);
} jz_probe_targets SEC(".maps");

/* Sniffer suspects -- devices that answered non-existent probe IPs */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u64);                     /* MAC packed into u64 */
    __type(value, struct jz_sniffer_suspect);
    __uint(max_entries, 1024);
    __uint(pinning, LIBBPF_PIN_BY_NAME);
} jz_sniffer_suspects SEC(".maps");

/* -- ARP Header Definition -- */

struct arphdr_eth_ip {
    __be16 ar_hrd;
    __be16 ar_pro;
    __u8   ar_hln;
    __u8   ar_pln;
    __be16 ar_op;
    __u8   ar_sha[6];
    __be32 ar_sip;
    __u8   ar_tha[6];
    __be32 ar_tip;
} __attribute__((packed));

/* -- Helpers -- */

static __always_inline __u32
arp_read_ip(const __be32 *ptr)
{
    __u32 ip = 0;
    __builtin_memcpy(&ip, ptr, sizeof(ip));
    return ip;
}

static __always_inline void
arp_write_ip(__be32 *ptr, __u32 ip)
{
    __builtin_memcpy(ptr, &ip, sizeof(ip));
}

static __always_inline __u64
mac_to_u64(const __u8 *mac)
{
    __u64 val = 0;
    __builtin_memcpy(&val, mac, 6);
    return val;
}

/* -- Main XDP Program -- */

SEC("xdp")
int jz_sniffer_detect_prog(struct xdp_md *xdp_ctx)
{
    struct rs_ctx *ctx = RS_GET_CTX();
    if (!ctx)
        return XDP_PASS;

    if (ctx->layers.eth_proto != bpf_htons(ETH_P_ARP)) {
        RS_TAIL_CALL_NEXT(xdp_ctx, ctx);
        return XDP_PASS;
    }

    void *data = (void *)(long)xdp_ctx->data;
    void *data_end = (void *)(long)xdp_ctx->data_end;
    struct ethhdr *eth = data;
    /* Mask l3_offset for BPF verifier packet range proof */
    __u16 l3_off = ctx->layers.l3_offset & RS_L3_OFFSET_MASK;
    struct arphdr_eth_ip *arp = (void *)data + l3_off;

    if ((void *)(eth + 1) > data_end)
        goto out;
    if ((void *)(arp + 1) > data_end)
        goto out;

    if (arp->ar_op != bpf_htons(2))
        goto out;
    if (arp->ar_hrd != bpf_htons(1))
        goto out;
    if (arp->ar_pro != bpf_htons(0x0800))
        goto out;
    if (arp->ar_hln != 6 || arp->ar_pln != 4)
        goto out;

    __u32 sender_ip = arp_read_ip(&arp->ar_sip);
    __u32 probe_ip = sender_ip;
    struct jz_probe_target *target = bpf_map_lookup_elem(&jz_probe_targets, &probe_ip);

    if (!target)
        goto out;

    target->status = 1;  /* response_received */

    __u64 now_ns = bpf_ktime_get_ns();
    __u64 suspect_key = mac_to_u64(arp->ar_sha);
    __u32 response_count = 1;
    struct jz_sniffer_suspect *suspect = bpf_map_lookup_elem(&jz_sniffer_suspects, &suspect_key);

    if (suspect) {
        __sync_fetch_and_add(&suspect->response_count, 1);
        suspect->last_seen_ns = now_ns;
        suspect->ip_addr = sender_ip;
        suspect->ifindex = ctx->ifindex;
        response_count = suspect->response_count;
    } else {
        struct jz_sniffer_suspect new_suspect = {};

        __builtin_memcpy(new_suspect.mac, arp->ar_sha, 6);
        new_suspect.ip_addr = sender_ip;
        new_suspect.first_seen_ns = now_ns;
        new_suspect.last_seen_ns = now_ns;
        new_suspect.response_count = 1;
        new_suspect.ifindex = ctx->ifindex;

        bpf_map_update_elem(&jz_sniffer_suspects, &suspect_key, &new_suspect, BPF_ANY);

        suspect = bpf_map_lookup_elem(&jz_sniffer_suspects, &suspect_key);
        if (suspect)
            response_count = suspect->response_count;
    }

    {
        struct jz_event_sniffer evt = {};

        evt.hdr.type = JZ_EVENT_SNIFFER_DETECTED;
        evt.hdr.len = sizeof(evt);
        evt.hdr.timestamp_ns = now_ns;
        evt.hdr.ifindex = ctx->ifindex;
        evt.hdr.vlan_id = ctx->ingress_vlan;
        __builtin_memcpy(evt.hdr.src_mac, arp->ar_sha, 6);
        evt.hdr.src_ip = sender_ip;

        __builtin_memcpy(evt.suspect_mac, arp->ar_sha, 6);
        evt.suspect_ip = sender_ip;
        evt.probe_ip = probe_ip;
        evt.response_count = response_count;

        RS_EMIT_EVENT(&evt, sizeof(evt));
    }

out:
    RS_TAIL_CALL_NEXT(xdp_ctx, ctx);
    return XDP_PASS;
}

char LICENSE[] SEC("license") = "GPL";
